global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'minhazur.rakin101@gmail.com'
  smtp_auth_username: 'minhazur.rakin101@gmail.com'
  smtp_auth_password: 'bcos lpfy bebh flcb'  # ğŸ” Use Gmail app password
  smtp_require_tls: true

route:
  receiver: email-alerts

receivers:
  - name: email-alerts
    email_configs:
      - to: 'minhazur.rakin101@gmail.com'
        send_resolved: true
